version: '2'
services:
  web:
    image: nginx:latest
    ports:
      - "1111:80"
    volumes:
      - ./code:/code/
      - ./conf/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./conf/nginx/conf/:/etc/nginx/conf/
      - ./conf/nginx/sites/:/etc/nginx/sites/
    networks:
      default:
        aliases:
          - renhead.devs

  php:
    build: .
    volumes:
      - ./code:/code
    environment:
      - php.extension=intl.so
